@url = http://localhost:5353/api/auth

### signin
POST {{url}}/signin HTTP/1.1
Content-Type: application/json

{
  "signin": "admin",
  "password": "Adminpass1."
}

### signin
POST {{url}}/signin HTTP/1.1
Content-Type: application/json

{
  "signin": "selahattin1",
  "password": "AdminPass1."
}

### 2fa verification
POST {{url}}/verify-2fa HTTP/1.1
Content-Type: application/json

{
  "username": "selahattin",
  "code": "234360"
}

### setup 2fa
POST {{url}}/setup-google-2fa HTTP/1.1
Content-Type: application/json

{
}

### signup
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
  "username": "selahattin1",
  "email": "selahattingungor53@hotmail.com",
  "password": "AdminPass1."
}

### Admin Paneline Erişim Denemesi (ROLE_USER ile)
GET http://localhost:5353/api/admin/projects HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### Admin Paneline Erişim Denemesi (ROLE_ADMIN ile)
GET http://localhost:5353/api/admin/projects HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### refresh token ile yeni access token alma
POST {{url}}/refresh HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### signout
POST {{url}}/signout HTTP/1.1
Content-Type: application/json

### analytics
POST http://localhost:5353/api/analytics/visit HTTP/1.1
Content-Type: application/json
