@url = http://localhost:5353/api/auth

### signin
POST {{url}}/signin HTTP/1.1
Content-Type: application/json

{
  "signin": "admin",
  "password": "Adminpass1."
}

### signin
POST {{url}}/signin HTTP/1.1
Content-Type: application/json

{
  "signin": "newuser",
  "password": "Newuser1!"
}

### signup
POST {{url}}/signup HTTP/1.1
Content-Type: application/json

{
  "username": "newuser",
  "email": "nesuser1@mail.com",
  "password": "Newuser1!"
}

### Admin Paneline Erişim Denemesi (ROLE_USER ile)
GET http://localhost:5353/api/admin/projects HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### Admin Paneline Erişim Denemesi (ROLE_ADMIN ile)
GET http://localhost:5353/api/admin/projects HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### refresh token ile yeni access token alma
POST {{url}}/refresh HTTP/1.1
Content-Type: application/json
# Cookie'ler otomatik gidecek

### signout
POST {{url}}/signout HTTP/1.1
Content-Type: application/json